///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TesteDemo1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputNameValid recording.
    /// </summary>
    [TestModule("60b5efbd-ad9a-4e05-ab51-379679ae7e7e", ModuleType.Recording, 1)]
    public partial class InputNameValid : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TesteDemo1Repository repository.
        /// </summary>
        public static TesteDemo1Repository repo = TesteDemo1Repository.Instance;

        static InputNameValid instance = new InputNameValid();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputNameValid()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputNameValid Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction1.Reset' at 15;4.", repo.RxMainFrame.RxTabIntroduction1.ResetInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabIntroduction1.Reset.Click("15;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction1.EnterYourName' at 88;11.", repo.RxMainFrame.RxTabIntroduction1.EnterYourNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabIntroduction1.EnterYourName.Click("88;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Wesley Ribeiro' with focus on 'RxMainFrame'.", repo.RxMainFrame.SelfInfo, new RecordItemIndex(2));
            repo.RxMainFrame.Self.EnsureVisible();
            Keyboard.Press("Wesley Ribeiro");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction1.BtnSubmitUserName' at 41;16.", repo.RxMainFrame.RxTabIntroduction1.BtnSubmitUserNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabIntroduction1.BtnSubmitUserName.Click("41;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome, Wesley Ribeiro!') on item 'RxMainFrame.RxTabIntroduction1.LblWelcomeMessage'.", repo.RxMainFrame.RxTabIntroduction1.LblWelcomeMessageInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabIntroduction1.LblWelcomeMessageInfo, "Text", "Welcome, Wesley Ribeiro!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction1.Reset' at 15;4.", repo.RxMainFrame.RxTabIntroduction1.ResetInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabIntroduction1.Reset.Click("15;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
