///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TesteDemo1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TesteDemo1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9529ec0a-491b-4584-9fab-61b4d55d02c5")]
    public partial class TesteDemo1Repository : RepoGenBaseFolder
    {
        static TesteDemo1Repository instance = new TesteDemo1Repository();
        TesteDemo1RepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the TesteDemo1Repository element repository.
        /// </summary>
        [RepositoryFolder("9529ec0a-491b-4584-9fab-61b4d55d02c5")]
        public static TesteDemo1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TesteDemo1Repository() 
            : base("TesteDemo1Repository", "/", null, 0, false, "9529ec0a-491b-4584-9fab-61b4d55d02c5", ".\\RepositoryImages\\TesteDemo1Repository9529ec0a.rximgres")
        {
            _rxmainframe = new TesteDemo1RepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9529ec0a-491b-4584-9fab-61b4d55d02c5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("8c8eb8a8-db88-42a9-bdf6-1f31c91a0020")]
        public virtual TesteDemo1RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TesteDemo1RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c8eb8a8-db88-42a9-bdf6-1f31c91a0020")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            TesteDemo1RepositoryFolders.RxTabIntroduction1Folder _rxtabintroduction1;
            RepoItemInfo _ranorexstudiodemoapplicationInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "8c8eb8a8-db88-42a9-bdf6-1f31c91a0020", "")
            {
                _rxtabintroduction1 = new TesteDemo1RepositoryFolders.RxTabIntroduction1Folder(this);
                _ranorexstudiodemoapplicationInfo = new RepoItemInfo(this, "RanorexStudioDemoApplication", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "68f47ccf-694d-4809-a0ab-3d0df1d88900");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c8eb8a8-db88-42a9-bdf6-1f31c91a0020")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c8eb8a8-db88-42a9-bdf6-1f31c91a0020")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item.
            /// </summary>
            [RepositoryItem("68f47ccf-694d-4809-a0ab-3d0df1d88900")]
            public virtual Ranorex.TitleBar RanorexStudioDemoApplication
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item info.
            /// </summary>
            [RepositoryItemInfo("68f47ccf-694d-4809-a0ab-3d0df1d88900")]
            public virtual RepoItemInfo RanorexStudioDemoApplicationInfo
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction1 folder.
            /// </summary>
            [RepositoryFolder("ddb9842e-08e8-443b-8d8a-08145485c038")]
            public virtual TesteDemo1RepositoryFolders.RxTabIntroduction1Folder RxTabIntroduction1
            {
                get { return _rxtabintroduction1; }
            }
        }

        /// <summary>
        /// The RxTabIntroduction1Folder folder.
        /// </summary>
        [RepositoryFolder("ddb9842e-08e8-443b-8d8a-08145485c038")]
        public partial class RxTabIntroduction1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtabintroductionInfo;
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _resetInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction1  folder.
            /// </summary>
            public RxTabIntroduction1Folder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction1", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "ddb9842e-08e8-443b-8d8a-08145485c038", "")
            {
                _rxtabintroductionInfo = new RepoItemInfo(this, "RxTabIntroduction", "", "", 30000, null, "b782d69a-eb85-48a1-af1d-82d9e9c4ff69");
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "97be167a-87ca-430a-8fb6-dcdc5c0a43c0");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "e66d8229-e0d7-468e-a5b0-049f7e389d47");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "6dbabeb0-be4e-4584-8259-525a45a975fd");
                _resetInfo = new RepoItemInfo(this, "Reset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", "", 30000, null, "0cc73c41-1db3-429b-a49d-d7e824f60990");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ddb9842e-08e8-443b-8d8a-08145485c038")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ddb9842e-08e8-443b-8d8a-08145485c038")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction item.
            /// </summary>
            [RepositoryItem("b782d69a-eb85-48a1-af1d-82d9e9c4ff69")]
            public virtual Ranorex.TabPage RxTabIntroduction
            {
                get
                {
                    return _rxtabintroductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabIntroduction item info.
            /// </summary>
            [RepositoryItemInfo("b782d69a-eb85-48a1-af1d-82d9e9c4ff69")]
            public virtual RepoItemInfo RxTabIntroductionInfo
            {
                get
                {
                    return _rxtabintroductionInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("97be167a-87ca-430a-8fb6-dcdc5c0a43c0")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("97be167a-87ca-430a-8fb6-dcdc5c0a43c0")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("e66d8229-e0d7-468e-a5b0-049f7e389d47")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("e66d8229-e0d7-468e-a5b0-049f7e389d47")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("6dbabeb0-be4e-4584-8259-525a45a975fd")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("6dbabeb0-be4e-4584-8259-525a45a975fd")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("0cc73c41-1db3-429b-a49d-d7e824f60990")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("0cc73c41-1db3-429b-a49d-d7e824f60990")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
